
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("sf_guard_user/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("sf_guard_user", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit sf_guard_user</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="first_name">First Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("first_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="last_name">Last Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("last_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="email_address">Email Of Address</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("email_address", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="username">Username</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("username", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="algorithm">Algorithm</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("algorithm", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="salt">Salt</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("salt", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="password">Password</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("password", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="is_active">Is Of Active</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("is_active", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="is_super_admin">Is Of Super Of Admin</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("is_super_admin", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="last_login">Last Of Login</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("last_login", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="location">Location</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("location", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="hometown">Hometown</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("hometown", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="locale">Locale</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("locale", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="timezone">Timezone</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("timezone", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="facebook_id">Facebook</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("facebook_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="facebook_verified">Facebook Of Verified</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("facebook_verified", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="facebook_link">Facebook Of Link</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("facebook_link", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="facebook_location_id">Facebook Of Location</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("facebook_location_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="facebook_hometown_id">Facebook Of Hometown</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("facebook_hometown_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created_at">Created</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("created_at", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="updated_at">Updated</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("updated_at", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="online">Online</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("online", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="cookie">Cookie</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("cookie", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="biography">Biography</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("biography", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="gender_id">Gender</label>
        </td>
        <td align="left">
            <?php echo $this->tag->select([
                "gender_id", 
                Gender::find(), 
                'using' => ['id', 'name']
            ]) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="birthday_date">Birthday Of Date</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("birthday_date", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="avatar_skin">Avatar Of Skin</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("avatar_skin", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="avatar_hair">Avatar Of Hair</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("avatar_hair", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="avatar_eyes">Avatar Of Eyes</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("avatar_eyes", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="profile_picture">Profile Of Picture</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("profile_picture", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="beelz">Beelz</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("beelz", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
