
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("sf_guard_user/new", "Create sf_guard_user")) ?>
</div>

<?php echo $this->tag->form(array("sf_guard_user/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search sf_guard_user</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="first_name">First Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("first_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="last_name">Last Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("last_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="email_address">Email Of Address</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("email_address", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="username">Username</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("username", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="algorithm">Algorithm</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("algorithm", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="salt">Salt</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("salt", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="password">Password</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("password", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="is_active">Is Of Active</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("is_active", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="is_super_admin">Is Of Super Of Admin</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("is_super_admin", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="last_login">Last Of Login</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("last_login", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="location">Location</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("location", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="hometown">Hometown</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("hometown", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="locale">Locale</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("locale", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="timezone">Timezone</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("timezone", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="facebook_id">Facebook</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("facebook_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="facebook_verified">Facebook Of Verified</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("facebook_verified", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="facebook_link">Facebook Of Link</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("facebook_link", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="facebook_location_id">Facebook Of Location</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("facebook_location_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="facebook_hometown_id">Facebook Of Hometown</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("facebook_hometown_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created_at">Created</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("created_at", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="updated_at">Updated</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("updated_at", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="online">Online</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("online", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="cookie">Cookie</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("cookie", "type" => "date")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
