<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("sf_guard_user/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("sf_guard_user/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Beelz</th>
            <th>First Of Name</th>
            <th>Last Of Name</th>
            <th>Email Of Address</th>
            <th>Username</th>
            <th>Algorithm</th>
            <th>Salt</th>
            <th>Password</th>
            <th>Is Of Active</th>
            <th>Is Of Super Of Admin</th>
            <th>Last Of Login</th>
            <th>Location</th>
            <th>Hometown</th>
            <th>Locale</th>
            <th>Timezone</th>
            <th>Facebook</th>
            <th>Facebook Of Verified</th>
            <th>Facebook Of Link</th>
            <th>Facebook Of Location</th>
            <th>Facebook Of Hometown</th>
            <th>Created</th>
            <th>Updated</th>
            <th>Online</th>
            <th>Cookie</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $sf_guard_user) { ?>
        <tr>
            <td><?php echo $sf_guard_user->id ?></td>
            <td><?php echo $sf_guard_user->sf_guard_user_profile->beelz ?></td>
            <td><?php echo $sf_guard_user->first_name ?></td>
            <td><?php echo $sf_guard_user->last_name ?></td>
            <td><?php echo $sf_guard_user->email_address ?></td>
            <td><?php echo $sf_guard_user->username ?></td>
            <td><?php echo $sf_guard_user->algorithm ?></td>
            <td><?php echo $sf_guard_user->salt ?></td>
            <td><?php echo $sf_guard_user->password ?></td>
            <td><?php echo $sf_guard_user->is_active ?></td>
            <td><?php echo $sf_guard_user->is_super_admin ?></td>
            <td><?php echo $sf_guard_user->last_login ?></td>
            <td><?php echo $sf_guard_user->location ?></td>
            <td><?php echo $sf_guard_user->hometown ?></td>
            <td><?php echo $sf_guard_user->locale ?></td>
            <td><?php echo $sf_guard_user->timezone ?></td>
            <td><?php echo $sf_guard_user->facebook_id ?></td>
            <td><?php echo $sf_guard_user->facebook_verified ?></td>
            <td><?php echo $sf_guard_user->facebook_link ?></td>
            <td><?php echo $sf_guard_user->facebook_location_id ?></td>
            <td><?php echo $sf_guard_user->facebook_hometown_id ?></td>
            <td><?php echo $sf_guard_user->created_at ?></td>
            <td><?php echo $sf_guard_user->updated_at ?></td>
            <td><?php echo $sf_guard_user->online ?></td>
            <td><?php echo $sf_guard_user->cookie ?></td>
            <td><?php echo $this->tag->linkTo(array("sf_guard_user/edit/" . $sf_guard_user->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("sf_guard_user/delete/" . $sf_guard_user->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("sf_guard_user/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("sf_guard_user/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("sf_guard_user/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("sf_guard_user/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
