
<?php echo $this->tag->form("item/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("item", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create item</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="category_id">Category</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("category_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="type_id">Type</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("type_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="price">Price</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("price", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="gender_id">Gender</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("gender_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="is_allowed">Is Of Allowed</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("is_allowed", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="is_active">Is Of Active</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("is_active", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="is_premium">Is Of Premium</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("is_premium", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created_at">Created</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("created_at", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="updated_at">Updated</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("updated_at", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="setting">Setting</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textArea(array("setting", "cols" => 30, "rows" => 4)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
