<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("item/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("item/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Category</th>
            <th>Type</th>
            <th>Name</th>
            <th>Price</th>
            <th>Gender</th>
            <th>Is Of Allowed</th>
            <th>Is Of Active</th>
            <th>Is Of Premium</th>
            <th>Created</th>
            <th>Updated</th>
            <th>Setting</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $item) { ?>
        <tr>
            <td><?php echo $item->id ?></td>
            <td><?php echo $item->category_id ?></td>
            <td><?php echo $item->type_id ?></td>
            <td><?php echo $item->name ?></td>
            <td><?php echo $item->price ?></td>
            <td><?php echo $item->gender_id ?></td>
            <td><?php echo $item->is_allowed ?></td>
            <td><?php echo $item->is_active ?></td>
            <td><?php echo $item->is_premium ?></td>
            <td><?php echo $item->created_at ?></td>
            <td><?php echo $item->updated_at ?></td>
            <td><?php echo $item->setting ?></td>
            <td><?php echo $this->tag->linkTo(array("item/edit/" . $item->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("item/delete/" . $item->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("item/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("item/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("item/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("item/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
