
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("sf_guard_user_profile/new", "Create sf_guard_user_profile")) ?>
</div>

<?php echo $this->tag->form(array("sf_guard_user_profile/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search sf_guard_user_profile</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="user_id">User</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("user_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="biography">Biography</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("biography", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created_at">Created</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("created_at", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="updated_at">Updated</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("updated_at", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="gender_id">Gender</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("gender_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="birthday_date">Birthday Of Date</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("birthday_date", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="avatar_skin">Avatar Of Skin</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("avatar_skin", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="avatar_hair">Avatar Of Hair</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("avatar_hair", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="avatar_eyes">Avatar Of Eyes</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("avatar_eyes", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="profile_picture">Profile Of Picture</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("profile_picture", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="beelz">Beelz</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("beelz", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
